### ISSUE TITLE
Milestone 3 Plan

### ISSUE THREAD

**Issue by hwilliams10** [UBC-MDS/DSCI_522_G410#41]
1. Download script

- [x]  Add relative path @hwilliams10 

2. 

- [x] Make makefile @hwilliams10 + test makefile @mglu123 

3. 

- [x] Add tests throughout @eyrakas (Analysis_overpaid) / @mglu123 (Cleaning) @merveshin (EDA)

4. 

- [x] Update Report @hwilliams10 

5. 

- [x] Update text / label size on plots/figures @merveshin 

6. If time:

- [ ] PREDICTION MODEL

Groups of variables:
1. Ball Skills
    - Crossing, Finishing, Heading, ShortPassing, Volleys, Dribbling, Curve, FKAccuracy, LongPassing, BallControl, LongShots
2. Physical
    - BMI, Acceleration, SprintSpeed, Agility, Reactions, Balance, ShotPower, Jumping, Stamina, Strength, Aggression
3. Game understanding
    - Interceptions, Position, Vision, Penalties, Composure, Marking, StandingTackle, SlidingTackle
4. General/Other
    - Age, Position, Domestic 

Steps: 
- Prepare correlation matrix for groups 1, 2, 3
- Choose top 2 or 3 variables from each of group 1 2 3, and all variables from group 4
- Run model and find top features

Create bar chart showing best features (should be coloured based on Group)

PREDICTION MODEL REPORT

Write report

EDA Report

**Comment by hwilliams10** [comment]
I just created a pull request with the latest report updates.
I think the only thing missing is a couple of tests on the `clean_leagues_table.r` script.

**Comment by hwilliams10** [comment]
We completed all the milestone 3 tasks and decided to leave out the prediction model again this week as we didn't have time.
